function pos_i = interpolate_position_size(pos1,pos2,frame1,frame2,current_frame)
pos_i=[interp1([frame1,frame2],[pos1(1),pos2(1)],current_frame)',...
	interp1([frame1,frame2],[pos1(2),pos2(2)],current_frame)',...
	interp1([frame1,frame2],[pos1(3),pos2(3)],current_frame)',...
	interp1([frame1,frame2],[pos1(4),pos2(4)],current_frame)'];
end